version: '3'

services:
    website:
        depends_on:
            - database
        build:
            context: ./.docker
            dockerfile: Dockerfile
            args:
                PHP_VERSION: ${PHP_VERSION}
                WEBSITE_NAME: ${WEBSITE_NAME}
        container_name: ${WEBSITE_NAME}
        ports:
            - ${APACHE_HTTP_PORT}:8080
        working_dir: /var/www/${WEBSITE_NAME}
        volumes:
            - ./:/var/www/${WEBSITE_NAME}/

    database:
        image: mysql:${DB_SERVER_VERSION}-debian
        container_name: ${WEBSITE_NAME}-database
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        volumes:
            - mysql-cms-data:/var/lib/mysql

volumes:
    mysql-cms-data:
