# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        storage.media.original:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/%media_storage_path%/original'
                lock: 0
                skip_links: false
                permissions:
                    file:
                        public: 0o644
                        private: 0o644
                    dir:
                        public: 0o755
                        private: 0o755
            visibility: ~ # default null. Possible values are 'public' or 'private'
            directory_visibility: ~ # default null. Possible values are 'public' or 'private'
            case_sensitive: true
            disable_asserts: false
        storage.media.150w:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/%media_storage_path%/150w'
                lock: 0
                skip_links: false
                permissions:
                    file:
                        public: 0o644
                        private: 0o644
                    dir:
                        public: 0o755
                        private: 0o755
            visibility: ~ # default null. Possible values are 'public' or 'private'
            directory_visibility: ~ # default null. Possible values are 'public' or 'private'
            case_sensitive: true
            disable_asserts: false
        storage.media.450w:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/%media_storage_path%/450w'
                lock: 0
                skip_links: false
                permissions:
                    file:
                        public: 0o644
                        private: 0o644
                    dir:
                        public: 0o755
                        private: 0o755
            visibility: ~ # default null. Possible values are 'public' or 'private'
            directory_visibility: ~ # default null. Possible values are 'public' or 'private'
            case_sensitive: true
            disable_asserts: false
        storage.media.800w:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/%media_storage_path%/800w'
                lock: 0
                skip_links: false
                permissions:
                    file:
                        public: 0o644
                        private: 0o644
                    dir:
                        public: 0o755
                        private: 0o755
            visibility: ~ # default null. Possible values are 'public' or 'private'
            directory_visibility: ~ # default null. Possible values are 'public' or 'private'
            case_sensitive: true
            disable_asserts: false
        storage.media.1280w:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/%media_storage_path%/1280w'
                lock: 0
                skip_links: false
                permissions:
                    file:
                        public: 0o644
                        private: 0o644
                    dir:
                        public: 0o755
                        private: 0o755
            visibility: ~ # default null. Possible values are 'public' or 'private'
            directory_visibility: ~ # default null. Possible values are 'public' or 'private'
            case_sensitive: true
            disable_asserts: false
        storage.media.1600w:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/%media_storage_path%/1600w'
                lock: 0
                skip_links: false
                permissions:
                    file:
                        public: 0o644
                        private: 0o644
                    dir:
                        public: 0o755
                        private: 0o755
            visibility: ~ # default null. Possible values are 'public' or 'private'
            directory_visibility: ~ # default null. Possible values are 'public' or 'private'
            case_sensitive: true
            disable_asserts: false
        storage.media.1920w:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/%media_storage_path%/1920w'
                lock: 0
                skip_links: false
                permissions:
                    file:
                        public: 0o644
                        private: 0o644
                    dir:
                        public: 0o755
                        private: 0o755
            visibility: ~ # default null. Possible values are 'public' or 'private'
            directory_visibility: ~ # default null. Possible values are 'public' or 'private'
            case_sensitive: true
            disable_asserts: false
        storage.media.2400w:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/%media_storage_path%/2400w'
                lock: 0
                skip_links: false
                permissions:
                    file:
                        public: 0o644
                        private: 0o644
                    dir:
                        public: 0o755
                        private: 0o755
            visibility: ~ # default null. Possible values are 'public' or 'private'
            directory_visibility: ~ # default null. Possible values are 'public' or 'private'
            case_sensitive: true
            disable_asserts: false
