when@prod:
    nelmio_security:
        # signs/verifies all cookies
        signed_cookie:
            names: ['']
            secret: '%env(APP_SECRET)%' # defaults to global %secret% parameter
            hash_algo: sha256 # defaults to sha256, see `hash_algos()` for available algorithms
        # prevents framing of the entire site
        clickjacking:
            paths:
                # '^/iframes/': ALLOW
                # '^/business/': 'ALLOW-FROM https://biz.example.org'
                # '^/local/': SAMEORIGIN
                '^/.*': DENY
            hosts:
                # - '^foo\.com$'
                # - '\.example\.org$'

        # prevents redirections outside the website's domain
        external_redirects:
            abort: true
            log: true
            forward_as: redirUrl
            # override: home
            # allow_list:
            #     - twitter.com
            #     - facebook.com

        # prevents inline scripts, unsafe eval, external scripts/images/styles/frames, etc
        csp:
            enabled: true
            hosts: []
            content_types: []
            hash:
                algorithm: sha256
            enforce:
                level1_fallback: false
                browser_adaptive:
                    enabled: false
                report-uri: '%router.request_context.base_url%/nelmio/csp/report'
                # default-src:
                #     - 'self'
                #     - 'strict-dynamic'
                #     - 'unsafe-inline'
                script-src:
                    - 'self'
                    - 'strict-dynamic'
                    - 'unsafe-inline'
                style-src:
                    - 'self'
                    - 'unsafe-inline'
                img-src:
                    - 'self'
                    - 'data:'
                font-src:
                    - 'self'
                    - 'data:'
                #     - 'strict-dynamic'
                    - 'unsafe-inline'
                # object-src:
                #     - 'self'
                frame-src:
                    - 'self'
                    - 'https://www.youtube.com'
                # block-all-mixed-content: true # defaults to false, blocks HTTP content over HTTPS transport
                # upgrade-insecure-requests: true # defaults to false, upgrades HTTP requests to HTTPS transport
            report_logger_service: monolog.logger.security
            compat_headers: true

        # disables content type sniffing for script resources
        content_type:
            nosniff: true

        # forces Microsoft's XSS-Protection with
        # its block mode
        xss_protection:
            enabled: true
            mode_block: true
            report_uri: '%router.request_context.base_url%/nelmio/xss/report'

        # Send a full URL in the `Referer` header when performing a same-origin request,
        # only send the origin of the document to secure destination (HTTPS->HTTPS),
        # and send no header to a less secure destination (HTTPS->HTTP).
        # If `strict-origin-when-cross-origin` is not supported, use `no-referrer` policy,
        # no referrer information is sent along with requests.
        referrer_policy:
            enabled: true
            policies:
                - 'no-referrer'
                - 'strict-origin-when-cross-origin'

        # forces HTTPS handling, don't combine with flexible mode
        # and make sure you have SSL working on your site before enabling this
        forced_ssl:
            enabled: true
            allow_list:
                - ^/unsecure/
            hosts:
                - ^\.example\.org$
            hsts_max_age: 31536000 # 1 year
            hsts_preload: true
            hsts_subdomains: true
            redirect_status_code: 302 # default, switch to 301 for permanent redirects

    # flexible HTTPS handling, read the detailed config info
    # and make sure you have SSL working on your site before enabling this
    #    flexible_ssl:
    #        cookie_name: auth
    #        unsecured_logout: false
